accounts/urls.py
from django.urls import path, include
from .import views

app_name = 'account'
urlpatterns = [
    path('', views.signin, name = 'signin'),
    path('signup/', views.signup, name = 'signup'),
    path('account_detail/<str:username>/', views.account_detail, name = 'account_detail'),
    path('user_detail/<str:username>/', views.user_detail, name = 'user_detail'),
    #--------------------------------------------------------------------------
    path('user_logout/', views.user_logout, name = 'user_logout'),
    path('out_membership/', views.out_membership, name = 'out_membership'),
    path('user_delete/', views.user_delete, name = 'user_delete'),
    path('follow/<str:username>/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path, include
from .import views
app_name = 'article'
urlpatterns = [
    path('articles/', views.articles, name = 'articles'),
    path('new_article/', views.new_article, name = 'new_article'),
    path('save_article/', views.save_article, name = 'save_article'),
    path('article_detail/<int:article_pk>/', views.article_detail, name = 'article_detail'),
    path("article_detail/<int:article_pk>/delete/", views.delete_article, name="delete_article"),
    path("article_detail/<int:article_pk>/delete/delete_complete/", views.delete_complete, name = 'delete_complete'),
    path('<int:article_pk>/like/', views.article_like, name='article_like'),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('articles/', include('articles.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from accounts.models import Users
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at= models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    #likes - article 모델이 해당 게시글을 좋아요 한 user id 목록을 얻고싶을 때 쓰는 필드
    #liked_product - user모델이 특정 유저가 좋아요 한 게시글의 id 목록을 얻고 싶을 때 쓰는 필드
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles', blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null = False, related_name='articles')
    
    def like_count(self):
        return self.likes.count()
    
    def __str__(self):
        return self.title

articles/forms.py
from .models import Article
from django import forms

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        widgets = {'content': forms.Textarea(attrs={'rows': 5, 'cols': 40}),}
class NewArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        widgets = {'content': forms.Textarea(attrs={'rows': 5, 'cols': 40}),}
        exclude = ('likes',)

articles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout 
from django.views.decorators.http import require_POST
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from .forms import ArticleForm, NewArticleForm
from .models import Article
from accounts.models import Users
# Create your views here.

@login_required
def articles(request):
    forms = Article.objects.all().order_by('-created_at')
    user = request.user
    context = {'forms':forms, 'user' : user}
    return render(request, 'article/article.html', context)
#--------------------------------------------------------
@require_http_methods(['GET', 'POST'])
@login_required
def new_article(request):
    if request.method == 'POST':
        form = NewArticleForm(request.POST)
        if form.is_valid():
            form.save(commit = False)
            form.author = request.user
            form.save()
            return redirect('article:articles')
    else:
        form = NewArticleForm()
        context = {
            'form' : form
        }
    return render(request, 'article/new_article.html', context)
#--------------------------------------------------------
@login_required
def save_article(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    new_article = Article.objects.create(title=title, content=content, author = request.user)
    return redirect("article:articles")
#--------------------------------------------------------
@require_http_methods(['GET', 'POST'])
@login_required
def article_detail(request, article_pk):
    article = get_object_or_404(Article, pk = article_pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance = article)
        if form.is_valid():
            form.save()
            return redirect('article:articles')
    else:
        form = ArticleForm(instance = article)
        context = {
            'form':form,
            'article':article
        }
        return render(request, 'article/article_detail.html', context)
#--------------------------------------------------------
@login_required
def delete_article(request, article_pk):
    del_article = Article.objects.get(pk=article_pk)
    context = {'del_article' : del_article}
    return render(request, 'article/delete_article.html', context)

@require_http_methods(['POST'])
@login_required
def delete_complete(request, article_pk):
    product = Article.objects.get(pk=article_pk)
    product.delete()
    return redirect("article:articles")
#--------------------------------------------------------
@login_required
def article_like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user in article.likes.all():
        article.likes.remove(request.user)
    else:
        article.likes.add(request.user)
    return redirect('article:article_detail', article_pk)
#--------------------------------------------------------

articles/templates/article/article.html
{% extends 'base.html' %}

{% block contents %}
<a href = "{% url 'account:user_detail' user.username %}">
    <button>프로필 편집</button>
</a><br>
<br>
<a href = "{% url 'article:new_article' %}">
    <button>새로운 글 쓰기</button>
</a><br>
<br>
<h2>올라온 품목 목록들</h2>
{% for form in forms %}
<hr>
<a href = "{% url 'article:article_detail' form.pk %}">
    <p>{{ form.title }}</p>
</a>
{% endfor %}
<button onclick="history.back()">돌아가기</button>
{% endblock contents %}

articles/templates/article/article_detail.html
{% extends 'base.html' %}

{% block contents %}
<h2>물건 상세 페이지</h2>
<p>제목: {{ article.title }}</p>
<p>작성자:</p><a href="{% url 'account:user_detail' article.author.username %}">{{ article.author.username }}</a>
<p>작성일시: {{ article.created_at }}</p>
<p>수정일시: {{ article.updated_at }}</p>

{% if request.user != article.author %}
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
{% endif %}
<!-- 현재 로그인한 사용자가 게시글 작성자인 경우에만 수정 폼 표시 -->
{% if request.user == article.author %}
    <form action="{% url 'article:article_detail' article.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="글 수정하기">
    </form><br>
{% endif %}

<form action="{% url 'article:article_like' article.pk %}" method="POST">
    {% csrf_token %}
    {% if user in article.likes.all %}
        <button type="submit">찜 취소</button>
    {% else %}
        <button type="submit">찜하기</button>
    {% endif %}
</form><br>

{% comment %} <a href = "{% url 'article:delete_article' article.pk %}">
    <input type="submit" value="글 삭제하기">
</a><br>
<br> {% endcomment %}

<!-- 삭제 버튼 -->
{% if request.user == article.author %}
    <a href="{% url 'article:delete_article' article.pk %}">
        <input type="submit" value="글 삭제하기">
    </a><br>
{% endif %}
<br>

<button onclick="history.back()">돌아가기</button>
{% endblock contents %}

articles/templates/article/delete_article.html
{% extends 'base.html' %}
{% block contents %}
<p> 정말 게시한 글을 삭제하시겠습니까? 삭제 하실려면 글 삭제를 눌러주세요!</p>
<form action="{% url 'article:delete_complete' del_article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="글 삭제">
</form>
<button onclick="history.back()">돌아가기</button>
{% endblock contents %}

articles/templates/article/new_article.html
{% extends 'base.html' %}

{% block contents %}
<h1> 새로운 중고 아이템 올리기! </h1>
<form action = "{% url 'article:save_article' %}" method = 'POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> 등록 </button>
</form>
<button onclick="history.back()">돌아가기</button>
{% endblock contents%}